CREATE SEQUENCE REQUEST_SEQ
    START WITH 1
    INCREMENT BY 50
    CACHE 100;

CREATE SEQUENCE REQUEST_AUDIT_SEQ
    START WITH 1
    INCREMENT BY 50
    CACHE 100;

CREATE SEQUENCE PUBLICATION_SEQ
    START WITH 100000
    INCREMENT BY 1
    CACHE 100;

CREATE TABLE REQUESTS (
    ID NUMBER(19) NOT NULL,
    NAME VARCHAR2(200 CHAR) NOT NULL,
    CONTENT VARCHAR2(4000 CHAR) NOT NULL,
    STATE VARCHAR2(20 CHAR) NOT NULL,
    PUBLICATION_NUMBER NUMBER(19),
    TERMINATION_REASON VARCHAR2(1000 CHAR),
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    VERSION NUMBER(19) DEFAULT 0 NOT NULL,

    CONSTRAINT PK_REQUESTS
        PRIMARY KEY (ID),

    CONSTRAINT UK_REQUESTS_PUBLICATION_NUMBER
        UNIQUE (PUBLICATION_NUMBER),

    CONSTRAINT CK_REQUESTS_STATE
        CHECK (
            STATE IN (
                'CREATED',
                'VERIFIED',
                'ACCEPTED',
                'PUBLISHED',
                'REJECTED',
                'DELETED'
            )
        )
);

CREATE TABLE REQUEST_AUDIT (
    ID NUMBER(19) NOT NULL,
    REQUEST_ID NUMBER(19) NOT NULL,
    FROM_STATE VARCHAR2(20 CHAR),
    TO_STATE VARCHAR2(20 CHAR),
    ACTION VARCHAR2(50 CHAR) NOT NULL,
    REASON VARCHAR2(1000 CHAR),
    ACTOR VARCHAR2(255 CHAR),
    OCCURRED_AT TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT PK_REQUEST_AUDIT
        PRIMARY KEY (ID),

    CONSTRAINT FK_REQUEST_AUDIT_REQUEST
        FOREIGN KEY (REQUEST_ID)
        REFERENCES REQUESTS(ID)
);

CREATE INDEX IX_REQUESTS_NAME
    ON REQUESTS (NAME);

CREATE INDEX IX_REQUESTS_CREATED_AT
    ON REQUESTS (CREATED_AT DESC);

CREATE INDEX IX_REQUESTS_STATE_CREATED_AT
    ON REQUESTS (STATE, CREATED_AT DESC);

CREATE INDEX IX_REQUEST_AUDIT_REQUEST_TIME
    ON REQUEST_AUDIT (REQUEST_ID, OCCURRED_AT DESC, ID);